### ISSUE TITLE
Trying to use tiptop-solid in the Mention extension

### ISSUE THREAD

**Issue by unutranyholas** [vriteio/tiptap-solid#1]
Hello! I found your bridge from solid to tiptap the most promising, but currently, I need help with the non-trivial task. Could you guide me in the right direction?

I want to adapt to solid the example from the official documentation provided; it's about the Mention extension: https://tiptap.dev/api/nodes/mention

I've copied the code from the example and tried to replace `ReactRenderer` with the `SolidRenderer` and adjust the args.

```
...
render: () => {
  let component
  let popup

  return {
    onStart: props => {
      component = new SolidRenderer(MentionList, {
        editor: props.editor,
        state: props.items,
      })
...
```

And somehow, it works. I can render the static popup but cannot figure out how to access the state inside the MentionList component. I admit that the library could not be designed for the use-case, but anyway, I would appreciate any suggestion.

**Comment by areknawo** [comment]
I haven't used the Mention extension yet, but I have used suggestion to implement a slash menu in Vrite. You should be able to access the state and the editor via e.g. `props.state`.

With the limited code snippet, I can't really tell if something else is causing the issue.

Check out the slash-menu extension in the Vrite codebase: https://github.com/vriteio/vrite/tree/main/apps/web/src/lib/editor/extensions/slash-menu. As I've said, it uses suggestion, so you should be able to use it as a rough reference.

Let me know if this helps.

**Comment by unutranyholas** [comment]
Yes, I've already found your example, and it works as intended, so the problem is probably in the Mention extension. I will try to figure out and share the results.

**Comment by unutranyholas** [comment]
Mysteriously, it started working.

Retrospectively, I was confused when I tried such code for the MentionList and got an empty object in the console.

```
const MentionList = (props) => {
  createEffect(() => {
    console.log("props", props);
  });
  return (
    <div>
      <For each={props.items}>{(item) => <div>{item}</div>}</For>
    </div>
  );
};
```

I still don't understand why it happens. The reactivity is a difficult thing 😄
