### ISSUE TITLE
how is this related to andi23rosca/tiptap-solid or not

### ISSUE THREAD

**Issue by apatrida** [vriteio/tiptap-solid#3]
This is similar to https://github.com/andi23rosca/tiptap-solid
but isn't.

Is this one superceeding the other, or not related?

**Comment by areknawo** [comment]
Not related. I've extracted this library from my larger [Vrite project](https://github.com/vriteio/vrite).

I've explored a few Tiptap-Solid integrations before starting the work on mine, but most didn't fit my needs (e.g. didn't support menus, Node views, etc.).

I don't recognize the library you've linked. It seems to cover the same feature set, so chances are it's just as good, if not better than this one.

From my side, `@vrite/tiptap-solid` works with the latest TipTap & Solid, and is actively maintained (even though not much activity is necessary) for the purpose of the Vrite project.

**Comment by apatrida** [comment]
But yours is missing correct exports to work with solid-start and solid without using the exact version you used.  Please check your exports against the other issue I filed.
