### ISSUE TITLE
This does not correctly export for a SolidJs library

### ISSUE THREAD

**Issue by apatrida** [vriteio/tiptap-solid#4]
This library does not correctly export as expected for a Solid Library

you must export what solid is expecting or you marry the user to the specific version of solid you used when creating the lib, which is not correct.

```
 "exports": {
    "solid": {
      "development": "./dist/dev.jsx",
      "import": "./dist/index.jsx"
    },
    "development": {
      "import": {
        "types": "./dist/index.d.ts",
        "default": "./dist/dev.js"
      }
    },
    "import": {
      "types": "./dist/index.d.ts",
      "default": "./dist/index.js"
    }
  },
```

and there are other exports, you should check with the https://github.com/solidjs-community/solid-lib-starter sample to see what you need to do.  Otherwise, people using this will get build time errors with other versions of SolidJS even compatible ones.

Note that the very similar library to yours does a correct export.

https://github.com/andi23rosca/tiptap-solid/blob/master/package.json

**Comment by areknawo** [comment]
I didn't have that problem using this lib in Vrite (even though Solid versions are sometimes different).
If your bundler supports it (e.g. Vite), there's the `source` key, which points directly to `.ts`/`.tsx` source files.

Did you experience any issues using the library as is?
And if so, do you have a `package.json` config (for potential PR) that fixes it?

**Comment by apatrida** [comment]
two things:

* solid team indicates that you must have the solid preset export
* doesn't work with solidjs 1.8.5 within solid-start

**Comment by areknawo** [comment]
Ok, I think pointing `solid` directly to the source files should work - will test it out.

For Solid-Start you should likely check out issue #2 - this library doesn't work in SSR, which might be the issue you're experiencing. SSR makes little sense for a WYSIWYG editor, so you should load the library only client-side.

**Comment by thednp** [comment]
@areknawo it must work in SolidStart, just inside Solid's  `clientOnly`, I've documented this with my [TinyMCE component for Solid](https://github.com/thednp/tinymce-solid#ssr-mode).

I would suggest you can do the same.

**Comment by areknawo** [comment]
@thednp I haven't used the library with Solid Start much. I'll check out `clientOnly` and add an example if it works
