### ISSUE TITLE
RangeError: Adding different instances of a keyed plugin (plugin$)

### ISSUE THREAD

**Issue by thednp** [vriteio/tiptap-solid#6]
I would suggest including in the README the same [solution](https://github.com/andi23rosca/tiptap-solid#issues) by @andi23rosca I also got the problem with your package or perhaps you found a different solution?

**Comment by areknawo** [comment]
I'm using `@tiptap/pm` instead of `prosemirror` packages directly and not getting any issues.
It's a solution provided and recommended by [TipTap](https://tiptap.dev/docs/editor/core-concepts/prosemirror) and should be the go-to option for resolving such conflicts.

Does it work for you?

**Comment by thednp** [comment]
Nope, the problem is still there. Perhaps including @tiptap/pm to optimize deps, let me try that.

**Comment by thednp** [comment]
Update: not working without that fix.

Try updating your tiptap/core and pm to latest and check again.

**Comment by areknawo** [comment]
Trying with Vrite (no SolidStart, just Vite SPA) - no error with the `@vrite/tiptap-solid` library, and all the TipTap packages updated to latest.

No problem adding the `optimizeDeps` note to `README.md` on my side, but if you can, you can share a minimal, reproducible example for me to debug and help you fix the issue.

**Comment by thednp** [comment]
@areknawo 
There you go [tiptap-issue.zip](https://github.com/user-attachments/files/16577625/tiptap-issue.zip)


* unzip and open folder in your editor
* pnpm install
* pnpm dev
* open http://localhost:3000/
* your browser will get the error `Uncaught RangeError: Adding different instances of a keyed plugin (plugin$)`
* browse `src/components` folder and check the `SolidEditor.tsx` file
* also check the vite.config.ts file as well

**Interestingly**, if you build and start, no problem there, only in dev. Perhaps using exports directly from proseMirror instead of `@tiptap/pm` might solve the issue, but IDK.

**Comment by areknawo** [comment]
Usually, I go with only `@tiptap/pm` and no direct imports from `prosemirror-` packages.

Interestingly, I split the StarterKit into individual extensions and it seems that GapCursor and DropCursor are the ones causing the issue. You can check here: [Archive.zip](https://github.com/user-attachments/files/16578198/Archive.zip)

Here's a possibly related issue with a comment on how to fix it: https://github.com/ueberdosis/tiptap/issues/3649#issuecomment-1934289709

That said, in my project, I do use GapCursor and DropCursor as individual extensions without any issues, so I'm not sure what's the problem here.

**Comment by thednp** [comment]
Thanks for the reply, will look into it.

**Comment by thednp** [comment]
@areknawo 
I believe we can close this.

I wish there was at least one example of a working tiptap editor somewhere with your package. Can you please point me in the right direction?

**Comment by areknawo** [comment]
@thednp The best example right now is within Vrite, but that's quite complex for an introduction: https://github.com/vriteio/vrite/blob/main/apps/web/src/views/editor/editor.tsx

Did you manage to run the editor from the archive (without the cursor extensions)?
If so, I'll close this, and open a new ticket for examples & better documentation (possibly researching this issue further as part of it).

**Comment by thednp** [comment]
Yes @areknawo thank you kindly. I got it to work by installing all extensions separately.

I will dissect your editor when I get some time, ATM have to figure out other stuff.
